// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: group.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addGroupIDToUser = `-- name: AddGroupIDToUser :exec
INSERT INTO
    group_users (group_id, user_id)
VALUES
    (
        ?,
        ?
    )
ON DUPLICATE KEY UPDATE
    group_id = ?, 
    user_id = ?
`

type AddGroupIDToUserParams struct {
	Groupid string
	Userid  string
}

func (q *Queries) AddGroupIDToUser(ctx context.Context, arg AddGroupIDToUserParams) error {
	_, err := q.db.ExecContext(ctx, addGroupIDToUser,
		arg.Groupid,
		arg.Userid,
		arg.Groupid,
		arg.Userid,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM
    ` + "`" + `groups` + "`" + `
WHERE
    id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, groupid string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, groupid)
	return err
}

const findAllUserID = `-- name: FindAllUserID :many
SELECT
    user_id
FROM
    group_users
WHERE
    group_id = ?
`

func (q *Queries) FindAllUserID(ctx context.Context, groupid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findAllUserID, groupid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGroup = `-- name: FindGroup :one
SELECT
    id,
    name,
    icon,
    created_at,
    updated_at
FROM
    ` + "`" + `groups` + "`" + `
WHERE
    id = ?
`

func (q *Queries) FindGroup(ctx context.Context, groupid string) (Group, error) {
	row := q.db.QueryRowContext(ctx, findGroup, groupid)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGroupName = `-- name: FindGroupName :one
SELECT
    name
FROM
    ` + "`" + `groups` + "`" + `
WHERE
    id = ?
`

func (q *Queries) FindGroupName(ctx context.Context, groupid string) (string, error) {
	row := q.db.QueryRowContext(ctx, findGroupName, groupid)
	var name string
	err := row.Scan(&name)
	return name, err
}

const saveGroup = `-- name: SaveGroup :exec
INSERT INTO
    ` + "`" + `groups` + "`" + ` (
        id,
        name,
        icon,
        created_at,
        updated_at
    )
VALUES
    (
        ?,
        ?,
        ?,
        NOW(),
        NOW()
    ) ON DUPLICATE KEY
UPDATE
    name = ?,
    icon = ?,
    updated_at = NOW()
`

type SaveGroupParams struct {
	ID   string
	Name string
	Icon sql.NullString
}

func (q *Queries) SaveGroup(ctx context.Context, arg SaveGroupParams) error {
	_, err := q.db.ExecContext(ctx, saveGroup,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Name,
		arg.Icon,
	)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE
    ` + "`" + `groups` + "`" + `
SET
    name = ?,
    icon = ?,
    updated_at = NOW()
WHERE
    id = ?
`

type UpdateGroupParams struct {
	Name string
	Icon sql.NullString
	ID   string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.Name, arg.Icon, arg.ID)
	return err
}
