// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          string
	UsersID     string
	Together    bool
	Description string
	Date        time.Time
	Important   bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
