// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          string
	UsersID     string
	Together    bool
	Description string
	Year        int32
	Month       int32
	Day         int32
	CreatedAt   time.Time
	StartDate   time.Time
	EndDate     time.Time
	UpdatedAt   time.Time
}

type Group struct {
	ID        string
	Name      string
	Icon      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GroupUser struct {
	GroupID string
	UserID  string
}

type User struct {
	ID        string
	LastName  string
	FirstName string
	Email     string
	Password  string
	Icon      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
