// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateEventInput struct {
	UserID      string    `json:"userId"`
	Together    bool      `json:"together"`
	Description string    `json:"description"`
	Year        int32     `json:"year"`
	Month       int32     `json:"month"`
	Day         int32     `json:"day"`
	Date        time.Time `json:"date"`
	StartDate   time.Time `json:"startDate"`
	EndDate     time.Time `json:"endDate"`
	Important   bool      `json:"important"`
}

type CreateGroupInput struct {
	Name string  `json:"name"`
	Icon *string `json:"icon,omitempty"`
}

type CreateUserInput struct {
	LastName  string  `json:"lastName"`
	FirstName string  `json:"firstName"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Icon      *string `json:"icon,omitempty"`
}

type Event struct {
	ID          string    `json:"id"`
	UserID      string    `json:"userID"`
	Together    bool      `json:"together"`
	Description string    `json:"description"`
	Year        int32     `json:"year"`
	Month       int32     `json:"month"`
	Day         int32     `json:"day"`
	Date        time.Time `json:"date"`
	CreatedAt   time.Time `json:"createdAt"`
	StartDate   time.Time `json:"startDate"`
	EndDate     time.Time `json:"endDate"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Important   bool      `json:"important"`
}

type Group struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Icon      *string   `json:"icon,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Users     []*User   `json:"users"`
}

type MonthlyEvent struct {
	Year  *int32 `json:"year,omitempty"`
	Month *int32 `json:"month,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateEventInput struct {
	Together    *bool      `json:"together,omitempty"`
	Description *string    `json:"description,omitempty"`
	Year        *int32     `json:"year,omitempty"`
	Month       *int32     `json:"month,omitempty"`
	Day         *int32     `json:"day,omitempty"`
	Date        *time.Time `json:"date,omitempty"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	EndDate     *time.Time `json:"endDate,omitempty"`
	Important   *bool      `json:"important,omitempty"`
}

type UpdateGroupInput struct {
	Name *string `json:"name,omitempty"`
	Icon *string `json:"icon,omitempty"`
}

type UpdateUserInput struct {
	LastName  *string `json:"lastName,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	Icon      *string `json:"icon,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	LastName  string    `json:"lastName"`
	FirstName string    `json:"firstName"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Icon      *string   `json:"icon,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Groups    []*Group  `json:"groups"`
	Events    []*Event  `json:"events"`
}
