name: Deploy to Koyeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: carsharesystem
    concurrency:
      group: koyeb-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: my-go-api           # Koyeb 上の App 名
          service-name: api-service     # Service 名
          git-branch: main
          git-docker-dockerfile: Dockerfile.koyeb
          privileged: true
          environment-variables: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            ROOTPASS=${{ secrets.ROOTPASS }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }}
            MAILGUN_PRIVATE_API_KEY=${{ secrets.MAILGUN_PRIVATE_API_KEY }}
            SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
            RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
          service-ports: "8080:http"    # Koyeb 側のポートマッピング
          service-routes: "/:8080"      # ルーティング設定
